baseURL = "https://gaborkevinbarta.com/developers-journal/"
publishDir = "docs"
languageCode = "en-us"
title = "A Developer's Journal"
googleAnalytics = "UA-141910422-1"

theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "green"

# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = true

# Provide a list of custom css files to load relative from the `static/` folder in the site root.
custom_css = ["css/custom.css"]


[[menu.shortcuts]]
name = "<i class='fas fa-globe'></i> Portfolio Website"
identifier = "pw"
url = "https://gaborkevinbarta.com/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github Repository"
identifier = "gr"
url = "https://github.com/gkevinb/developers-journal"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> Hugo Learn Theme"
identifier = "htld"
url = "https://themes.gohugo.io/theme/hugo-theme-learn/en"
weight = 15